### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by MeboGit** [wangfei1975/superlog#22]
C:\tools\superlog-master>gradlew
:clean UP-TO-DATE
:genBuildInfo
fatal: not a git repository (or any of the parent directories): .git
                                                                     :genBuildInfo FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\tools\superlog-master\genbuildinfo.gradle' line: 3

* What went wrong:
Execution failed for task ':genBuildInfo'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.235 secs

**Comment by wangfei1975** [comment]
Thank you for comments. The build script need to run inside a GIT repo. Please clone the source from GITHUB.

**Comment by MeboGit** [comment]
Thanks for your reply.

In README.md it says:

Build the project by either executing
  * gradlew (eg if you don't have Gradle installed)
  * or the Gradle build file (build.gradle)

So executing gradlew for me would mean "execute gradlew.bat"?!

Sorry, but I'm not a Java Dev, just C/C++ (without gradle). 

Or is this tool only to be used by gradle/git/java professionals?

**Comment by wangfei1975** [comment]
Yes. If build it on Windows, you will need to execute gradlew.bat.
The Gradle and GIt are only required if you build or contribute to the project.  If you just use the tool, no need Gradle or GIT installed on your computer.

The tool is for read and analyze Android logcat logs. No need to be java professionals.

**Comment by MeboGit** [comment]
Ok, but if gradlew.bat is only for building and I don't need Gradle or GIT and I just want to use the tool for logcat logs then my very final question is: 

How do I start this tool?

**Comment by wangfei1975** [comment]
Go to release and download the latest build:
https://github.com/wangfei1975/superlog/releases
Use following command to start the tool 
 java -jar superlog-1.0-standalone.jar

or double click the jar on Windows if you have proper configured Java environment.

**Comment by MeboGit** [comment]
Ah, ok, I did not see/know that.

Thank you for your support!
